version: '2' #指定docker-compose版本
services:
  tank-mysql:
    build:
      context: ./db # Dockerfile路径
    environment:
      MYSQL_ROOT_PASSWORD: crowontheplane # 初始化数据库root用户的密码
    restart: always
    container_name: tank-mysql
    ports:
      - 3307:3306
  app:
    build:
      context: ./tank-app
    restart: always
    container_name: tank-app
    ports:
      - 8080:8080
